### ISSUE TITLE
Remove solid_body_rotation_split from docs

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/mesh-adaptation-docs#18]
Thanks @ddundo. Please address my comment and also open a PR to update https://github.com/mesh-adaptation/mesh-adaptation-docs accordingly.

_Originally posted by @jwallwork23 in https://github.com/mesh-adaptation/goalie/pull/176#pullrequestreview-2013080752_

**Comment by ddundo** [comment]
@jwallwork23 could you please give me permission to push to this repo too?

And I only need to update the index, right? :)

**Comment by jwallwork23** [comment]
> @jwallwork23 could you please give me permission to push to this repo too?

Done.

> And I only need to update the index, right? :)

Yeah, thanks.

**Comment by ddundo** [comment]
Thanks!
