### ISSUE TITLE
Installing on non-Ubuntu

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/mesh-adaptation-docs#35]
I just installed Firedrake on Red Hat Linux using the mesh-adaptation-docs installation script that we have here. It worked out of the box, apart from having to pass `–no-package-manager` option, as per Firedrake's installation instructions. Maybe we could be more explicit in what our installation instructions assume and in any case refer to Firedrake's installation page for details/debugging

**Comment by jwallwork23** [comment]
Yeah I agree it makes sense to have different scripts for different platforms. However, perhaps it would make sense to refactor to use Make so that we can include the appropriate Makefile for the platform in use? e.g., `config/ubuntu.mk`, `config/redhat.mk`.

**Comment by ddundo** [comment]
Sounds like a good idea to me!
