### ISSUE TITLE
Update Install instructions to use Makefile

### ISSUE THREAD

**Issue by acse-ej321** [mesh-adaptation/mesh-adaptation-docs#38]
It looks as if the `install_firedrake.sh` was recently removed in preference of a `Makefile`. It would be good to update te documented installation instructions to reflect this change.

**Comment by jwallwork23** [comment]
Good point! I should've done this indeed.

**Comment by jwallwork23** [comment]
@acse-ej321 please could you check you're happy with my updates to https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Installation-Instructions? If so, please close this issue, thanks.

**Comment by ddundo** [comment]
More changes are necessary :) see #73

**Comment by acse-ej321** [comment]
@ddundo - I think most users may already have Firedrake installed. However, some of the PETSc flags set for Animate and Goalie might not have been included in their setups - particularly `--download-mmg` which is not widely used. An existing Firedrake installation with additional PETSc flags appears to require a near-complete `firedrake-update --rebuild` to update. So, it is probably worth leaving first, as it is the key dependency for the others, but maybe adding a description of how to update a current Firedrake installation?

**Comment by acse-ej321** [comment]
@jwallwork23 - The instructions for working with the Makefile are clearer. However, the makefile requires all the contents of the `install` folder to run, including the `config` folder, which is not included in the installation instructions. 
Until the `FIREDRAKE_CONFIGURE_OPTIONS` become larger, a temporary solution could be adding the contents of the `config/*.mk` files directly into the current flow control statement at the beginning of the Makefile. That would require no additional changes to the current installation instructions. 
Otherwise, @ddundo's suggestion above seems like a good way to maintain the current, more pythonic file structure. 
The last idea is to have the user download just the install folder, cd into it, and then run the Makefile.

**Comment by ddundo** [comment]
You're right! And this all sounds great to me @acse-ej321, thanks a lot :)

**Comment by jwallwork23** [comment]
> @jwallwork23 - The instructions for working with the Makefile are clearer. However, the makefile requires all the contents of the `install` folder to run, including the `config` folder, which is not included in the installation instructions. Until the `FIREDRAKE_CONFIGURE_OPTIONS` become larger, a temporary solution could be adding the contents of the `config/*.mk` files directly into the current flow control statement at the beginning of the Makefile. That would require no additional changes to the current installation instructions.

Yes, I agree. For now let's just inline the contents of `ubuntu.mk` (etc.) into the Makefile. (It just sets the `FIREDRAKE_CONFIGURE_OPTIONS` env variable). If one of you has time to do this that'd be much appreciated - I'm unlikely to get to this for a few days.
