### ISSUE TITLE
Reusing workflows

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/mesh-adaptation-docs#45]
I just found out that [reusable workflows](https://docs.github.com/en/actions/sharing-automations/reusing-workflows) exist, which I think would be good for us. In all 3 repos we have the identical `citation_check.yml` workflow and an almost identical `test_suite.yml`. So it's a bit of a hassle that we have to edit all 3 when making changes. We could host these common workflows in `mesh-adaptation-docs` and make smaller workflows in the 3 repos that would call them. What do you think @jwallwork23?

**Comment by jwallwork23** [comment]
Yeah I must admit the recent changes did make me think of the "shotgun surgery" bad "code smell" that people refer to in software engineering. I hadn't heard of this before, sounds like a great idea!

**Comment by jwallwork23** [comment]
@ddundo Would you mind doing the same for the Docker build workflows? They have the same pattern and we are going to bring UM2N under the `mesh-adaptation` organisation, which will require another bespoke Docker build, implying another such workflow.

**Comment by ddundo** [comment]
Sure :)

**Comment by jwallwork23** [comment]
In which case I guess more sensible filenames would be `docker_petsc-parmmg.yml` and `docker_firedrake-parmmg.yml`
