### ISSUE TITLE
Citations don't render in html locally

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/mesh-adaptation-docs#50]
Building the website both locally and on the new docker image raises warnings such as `/data3/mesh-adaptation-docs/docs/source/demos/solid_body_rotation.py.rst:21: WARNING: could not find bibtex key "LeVeque:1996"` and the citations don't render in html for me. They just appear as empty brackets `[]`. @jwallwork23 gets the same warnings on his local build but citations render for him

**Comment by jwallwork23** [comment]
Hm it's not working for me either now, so the latest website build is missing references. Do you have any idea how to fix this @acse-ej321?

**Comment by jwallwork23** [comment]
I propose that we move the bibtex files out of the different repos and merge them in the docs repo, to make things much simpler.

**Comment by acse-ej321** [comment]
@jwallwork23 I started a branch for this issue and it seems to be rendering for me locally now. I took the middle-ground approach between your proposal and the current file structure. The main problem was multiple duplicate references in various `reference.bib` files. This was not helped by multiple citation keys for the same references.

What I have done locally, and am proposing tentatively for a PR is:
- standardized the citation reference structure across the files
- renamed all the citation keys following the `Firedrake` format of `<first author>:<year>` to be consistent, if somewhat of an arbitrary choice.
- I left the demo references in <package>/demo/demo_references.bib and created `source_references.bib` to hold the references applicable to the source/docs
- modified the Makefile to combine all the references into an empty `source/references.bib`
- deleted all the extra reference files and linked to only `references.bib` file.

For this to work though I need to make the citation edits to the demos and docstrings in the main repositories. I was wondering the best way to document this? Do I open a pull request in each and cross-reference back to one here?

**Comment by jwallwork23** [comment]
Great, thanks for this @acse-ej321.

> For this to work though I need to make the citation edits to the demos and docstrings in the main repositories. I was wondering the best way to document this? Do I open a pull request in each and cross-reference back to one here?

Yeah unfortunately at present it's probably best to just open PRs for each repo and link them together in their descriptions so that the reviewer reviews all of them together. Don't worry about opening issues for this on the other repos, though.
