### ISSUE TITLE
Create Docker container for UM2N environment

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/mesh-adaptation-docs#58]
The dependencies of UM2N take more than 15 minutes to install on the CI. It would be better to create a bespoke Docker container off of the Firedrake one that has them pre-built.

**Comment by ddundo** [comment]
@jwallwork23 I see you took this over now. Do you mind if I take it and do it today? It's blocking #4 so I'd be keen to do it asap and test that it works

**Comment by jwallwork23** [comment]
I already made a start by cherry-picking @chunyang-w's commits and putting them into mesh-adaptation-docs. Will open a PR, hopefully will have it resolved shortly.

**Comment by ddundo** [comment]
Ah perfect, thanks!
