### ISSUE TITLE
UM2N automated Docker build unable to push

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/mesh-adaptation-docs#69]
Following #59, the merge into main CI failed to push the UM2N Docker image to gchr:
https://github.com/mesh-adaptation/mesh-adaptation-docs/actions/runs/11989040355/job/33424975305

This is odd because the settings all seem right for allowing actions to push.

**Comment by ddundo** [comment]
I went to look into this out of curiosity, but I can't find what you linked in https://github.com/mesh-adaptation/mesh-adaptation-docs/actions. What triggered it? 

The last run of that workflow succeeded, which was triggered by the merge into the main branch: https://github.com/mesh-adaptation/mesh-adaptation-docs/actions/runs/11989040355/ . Notice that it's the same action number 11989040355 as what you linked - which is odd. And the UM2N package on ghcr says that it was last updated 2 hours ago

But anyway... it seems to work? :)

**Comment by jwallwork23** [comment]
Hm, I reran it and maybe I misread the result. I guess we can close this then, thanks.
