### ISSUE TITLE
config/ubuntu.mk missing

### ISSUE THREAD

**Issue by bueler** [mesh-adaptation/mesh-adaptation-docs#73]
Trying the first option on the intallation page gave me a missing file error:
```
$ curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/Makefile
curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/petsc_configure_options.txt
make install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2818  100  2818    0     0  11030      0 --:--:-- --:--:-- --:--:-- 11007
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   319  100   319    0     0   1239      0 --:--:-- --:--:-- --:--:--  1241
Makefile:14: config/ubuntu.mk: No such file or directory
make: *** No rule to make target 'config/ubuntu.mk'.  Stop.
```
Thanks.

**Comment by ddundo** [comment]
Hi @bueler, nice to see you trying out the software here! Sorry about this, we forgot to edit the wiki to say that we should also download the appropriate config file (i.e. `ubuntu.mk`) from https://github.com/mesh-adaptation/mesh-adaptation-docs/tree/main/install/config . So making a `config` directory and doing `curl -O https://raw.githubusercontent.com/mesh-adaptation/mesh-adaptation-docs/main/install/config/ubuntu.mk` should do it. 

But @jwallwork23 this seems like a lot of extra commands. Maybe we could just have user download the first `Makefile` and then have the two config files be automatically downloaded/read in by the script?

**Comment by ddundo** [comment]
We reverted this change and removed these config files (ubuntu.mk etc), so the installation instructions are again up to date :)
